import { homedir } from 'node:os';
import { join } from 'node:path';

export const LATEST_VERSION = '2.5.1';
// The /web subpath is required — it exports the <interact-element> custom element.
export const INTERACT_CDN = `https://esm.sh/@wix/interact@${LATEST_VERSION}/web`;
export const PRESETS_CDN = 'https://esm.sh/@wix/motion-presets';
export const DRAFTS_DIR = '.drafts';
// Generated prose guidelines ("convert to prompt" output) live here.
export const PROMPTS_DIR = 'Ani-Mate Prompts';

// Directories never scanned for animation files.
export const IGNORED_DIRS = new Set([
  'node_modules', '.git', '.drafts', '.backups',
  'analysis', 'explorer-screenshots', 'docs', 'validator', '.cursor',
  PROMPTS_DIR,
  // Prompts generated by the old interact-demo-to-guideline format, parked for
  // reference while the library is rebuilt with interact-example-builder.
  'legacy-prompts',
]);

// Files at any level that are not animations.
export const IGNORED_FILES = new Set(['explorer.html']);

// Top-level dirs whose `.md` files are shown in the Examples tab as
// markdown-doc examples (rendered as text, not live-previewed). Everywhere
// else, only `.html` counts as an example — this keeps repo docs/notes/READMEs
// out of the tab. Add a dir here to surface its `.md` animation docs.
export const EXAMPLE_MD_DIRS = new Set(['interactor-examples']);

// "Convert to prompt" runs the interact-example-builder skill. The shared
// globals (house rules + adaptation ladder) and the append-only suggested-globals
// inbox live outside this repo until they are folded into interact-xp at the end
// of the conversion effort.
export const EXAMPLE_SKILL_DIR = process.env.EXAMPLE_SKILL_DIR
  || join(homedir(), '.claude/skills/interact-example-builder');
export const GLOBALS_DIR = process.env.GLOBALS_DIR
  || join(homedir(), 'Documents/Dev/Wix/POC for Amit Kaufman/globals');
export const SUGGESTED_GLOBALS_FILE = join(GLOBALS_DIR, 'suggested-globals.md');

export const PLAYGROUND_REPO = process.env.PLAYGROUND_REPO || join(homedir(), 'Documents/Dev/Wix/interact-xp');
export const PLAYGROUND_URL = process.env.PLAYGROUND_URL || 'http://localhost:5173';
export const SECTION_INSTRUCTION =
  'Apply the animation pattern described in the example to this section. Follow its Selector Contract and Interact Template, adapting the roles to this section’s DOM. Return only the experience config.';
